### ISSUE TITLE
Conker’s Bad Fur Day, HLE RSP, polef 

### ISSUE THREAD

**Issue by kode54** [joshware/lazyusf2#2]
sparse41 and sparse43 play back incorrectly and may even crash the emulator. Both appear to use naudio_14, with the zero table values, so conventional polef? Unless this is wrong for CBFD.

**Comment by derselbst** [comment]
Hi, thanks for looking into this.

The resonant IIR low-pass-filter heard in sparse3d (RockSolid) works well, since @joshware has fixed it a few years ago. I believe this is a different issue, which never worked before.

When you inspect the MIDI of e.g. sparse41, you'll find that Mr. Beanland has placed a CC35 with value 10 into channel 2 (zero-based counting). This will trigger some kind of "overdrive" effect heard in the very first seconds of the song.

That same instrument is playing again ~19 seconds, this time however it's on channel 5, and CC35 is set to a value of 0. RockSolid also implicitly keeps CC35 at 0, hence CC35=0 means "IIR low-pass filter". But what does CC35=10 mean?

With HLE enabled, your plugin will even output an error like `unknown audio command: 00000 bla`.

The crash that you experienced may be due to a bug in Josh's original IIR HLE implementation. It has been fixed at mupen64plus: mupen64plus/mupen64plus-rsp-hle/pull/83

**Comment by kode54** [comment]
Yeah, I found the problem with my code. Beside that crash bug being fixed, I was also spuriously logging all warnings, which also broke execution of the emulator. I've disabled warn logging now.

**Comment by derselbst** [comment]
Sorry @kode54, but while your recent findings improve the situation, it still sounds different to LLE: That overdrive effect I described is completely missing in HLE.

**Comment by joshware** [comment]
Wow, with that bug I'm surprised it worked at all. Sorry about that, my bad.

Though the missing effect is interesting, I'll look into it and see what I can dig up. Maybe it's that unknown alist call
